version: "3"
services:
  # frontend:

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ".backend:/app"
  # db:
  # image: mysql:8.0
  # environment:
  #   MYSQL_ROOT_PASSWORD: password
  # command: --default-authentication-plugin=mysql_native_password
  # volumes:
  #   - mysql-data:/var/lib/mysql
  #   - /tmp/dockerdir:/etc/mysql/conf.d/
  # ports:
  #   - 3306:3306
