name: Rails GitHub Actions
on: [push]
jobs:
  test-about-rails:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          cd backend
          gem install bundler
          bundle install
      - name: Set up MySQL Client
        run: sudo apt-get install -y default-mysql-client
      - name: Set up Rails
        run: |
          cd backend
          bundle exec rake db:create db:migrate RAILS_ENV=test
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Run Rails Tests
        run: bundle exec rails test
